### ISSUE TITLE
Doesn't work on Wayland (Ubuntu 22.04)

### ISSUE THREAD

**Issue by lamyergeier** [faf0/sct#34]
Doesn't work on Ubuntu 22.04? Is it due to wayland?

**Comment by zvezdochiot** [comment]
Hi @lamyergeier .

What exactly doesn't work? How exactly does it not work?

PS: Use [`redshift`](https://github.com/jonls/redshift)
```sh
$ redshift -m list
```

**Comment by lamyergeier** [comment]
@zvezdochiot  when I type the following color temperature does not change:

```
sct 2000
sct 6000
```

Are you suggesting that sct does not support wayland and we should use redshift?

**Comment by zvezdochiot** [comment]
Hi @lamyergeier .

Yes, use [`redshift`](https://github.com/jonls/redshift).

PS: This utility has been renamed to `xsct` a long time ago. What are you using?
https://github.com/faf0/sct/blob/1bfe07511820065d8bed2045776e25b6f42a8793/Makefile#L9
https://github.com/faf0/sct/blob/2a62dd4234066a2e87ba3347a54d71145f25fd73/CHANGELOG#L30-L31

**Comment by lamyergeier** [comment]
I am sorry, I was using another utility which does the same thing and is called as sct. Now I uninstalled that and I tried to compile xsct as follows using [sct/Makefile at master · faf0/sct](https://github.com/faf0/sct/blob/master/Makefile)

```
cc -Wall -Wextra -Werror -pedantic -std=c99 -O2 -I /usr/X11R6/include xsct.c -o xsct -L /usr/X11R6/lib -s -lX11 -lXrandr -lm
xsct.c:7:10: fatal error: X11/Xatom.h: No such file or directory
    7 | #include <X11/Xatom.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:15: xsct] Error 1
```

So, xsct doesn't support wayland. Right?

**Comment by zvezdochiot** [comment]
Hi @lamyergeier .

How many times should "this" be repeated?
